services:
    chrome:
        container_name: ddev-${DDEV_SITENAME}-chrome
        image:  isholgueras/chrome-headless:latest
        restart: unless-stopped
        labels:
            com.ddev.site-name: ${DDEV_SITENAME}
            com.ddev.approot: $DDEV_APPROOT
        volumes:
            - ddev-global-cache:/mnt/ddev-global-cache
            - ".:/mnt/ddev_config"
        external_links:
            - "ddev-router:${DDEV_HOSTNAME}"
        shm_size: 1024M
        cap_add:
            - SYS_ADMIN
        ports:
            - '9222:9222'
